### ISSUE TITLE
Enable STAMINA saved state space to work with STORM

### ISSUE THREAD

**Issue by zgzn** [fluentverification/stamina-prism#10]
Storm can actually read three different kinds of explicit input files:

* The one from MRMC (Storms predecessor), see option `—explicit <.tra file> <.lab file>` and optionally `—staterew <.rew file> —transrew <.rew file>` for rewards
* Our “own” DRN Format, see option `—explicit-drn <.drn file>`
* The format of IMCA (A Markov Automaton analysis tool), see option `—explicit-imca` <.imca file>`

PRISM already has facilities to export the models in MRMCs format. You can find example files in `storm/resources/examples/testfiles`.

**Comment by ifndefJOSH** [comment]
This would need a newer version of PRISM in order to work (for MRMC specifically). PRISM v4.5 throws a "Not Implemented Yet" exception when the `Prism.EXPORT_MRMC` option is passed into `.export*ToFile()` (see `StaminaModelChecker.java:370-ish` in the `refactor` branch). Please note that in `refactor` (which we ~~could~~ probably should also upgrade to work with PRISM v4.7 which supports this export) now has a `-mrmc/--mrmc` flag.

**Comment by ifndefJOSH** [comment]
I have just checked, and `v4.7` of PRISM will *not* work with STAMINA out of the box. We get the following deprication of `parser.ast.Declaration parser.VarList.getDeclaration()`:

```
Exception in thread "main" java.lang.NoSuchMethodError: 'parser.ast.Declaration parser.VarList.getDeclarat
        at stamina.StaminaModelGenerator.<init>(StaminaModelGenerator.java:104)
        at stamina.StaminaModelChecker.modelCheckStamina(StaminaModelChecker.java:123)
        at stamina.StaminaCL.run(StaminaCL.java:164)
        at stamina.StaminaCL.main(StaminaCL.java:84)
```

**Comment by ifndefJOSH** [comment]
As of now, STAMINA works with PRISM v4.8 (commit hash [ce9406d](https://github.com/fluentverification/stamina-prism/pull/21/commits/ce9406d7fbefd8bca7033ef270df9180d09d1d88))
